@echo off
chcp 65001 > nul
REM ===================================================================
REM  KJC Studio - reopen every named Claude session
REM
REM  Generated by tools/update-sessions.py. Do not edit by hand.
REM  A session joins this list once it has been given a name
REM  with /rename - nothing here needs changing.
REM
REM  KEEP THIS FILE ASCII-ONLY. After `chcp 65001` cmd miscounts the
REM  bytes of its own batch file, so Korean text below makes it lose
REM  its place mid-line. The Korean output comes from Python.
REM ===================================================================

cd /d "%~dp0"

REM Rescan the list, then open each session that is not already up.
python tools\update-sessions.py --open

ping -n 3 127.0.0.1 > nul
