# -*- coding: utf-8 -*-
"""
세션 목록을 훑어서 두 파일을 다시 만든다.

  resume-sessions.bat  이름이 붙은 세션을 각각 새 창으로 여는 실행 파일
  SESSIONS.md          세션 목록과 복구 방법을 적은 문서

세션이 늘거나 이름이 바뀌면 이 스크립트를 다시 돌리면 된다.
resume-sessions.bat 은 실행될 때 스스로 이 스크립트를 먼저 부르므로,
평소에는 따로 돌릴 일이 없다.

세션 기록은 Claude Code 가 아래에 남긴다.
  %USERPROFILE%\\.claude\\projects\\C--work-KJCStudio\\<세션ID>.jsonl
이름은 `/rename` 을 쓴 기록에서 찾는다. 이름이 없는 세션은 목록에서 뺀다.
"""
import io
import json
import os
import re
import sys
from datetime import datetime

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGS = os.path.join(os.path.expanduser("~"), ".claude", "projects", "C--work-KJCStudio")
BAT = os.path.join(REPO, "resume-sessions.bat")
DOC = os.path.join(REPO, "SESSIONS.md")

# 이름에 쓸 수 있는 글자만 받는다. 넓게 잡으면 대화에 섞인 코드 조각까지
# 이름으로 잡히는 일이 생긴다 (실제로 그랬다).
RENAME = re.compile(r"Session renamed to: ([가-힣A-Za-z0-9_\-. ]{1,30})")


def find_name(path):
    """마지막 rename 기록을 찾는다. 기록 줄의 **종류까지** 본다.

    전에는 파일 전체를 글자로 훑어 마지막 매치를 썼다. 그러다 세션 하나가
    **남의 이름을 달았다.** 2026-09-16 에 `작업우선순위` 세션이 목록에
    `홈페이지_정리` 로 올라왔다. 그 세션 기록을 세어보니 이랬다.

        '작업우선순위'   1회   ← 진짜 자기 이름
        '홈페이지_정리'   2회   ← 남의 기록을 읽다가 들어온 것

    그 세션은 **다른 세션의 기록을 읽는 것이 일**이라, 읽은 내용이 자기
    대화에 남는다. 글자만 보면 남 얘기와 자기 이름을 구분할 수 없다.

    진짜 rename 은 이렇게 생겼다.

        {"type":"system","subtype":"local_command",
         "content":"<local-command-stdout>Session renamed to: 개념정의</...>"}

    읽다가 들어온 것은 `"type":"tool_use"` 안의 명령 문자열이다.
    그래서 **`type` 이 `system` 인 줄만** 인정한다.

    예전에 이름이 `([^` 로 잡혔던 것도 같은 뿌리였다. 그때는 정규식을
    좁혀 막았는데, 이름 규칙에 맞는 남의 이름은 그것으로 못 거른다.
    """
    name = ""
    try:
        with io.open(path, encoding="utf-8", errors="ignore") as fp:
            for line in fp:
                if "Session renamed to:" not in line:
                    continue
                try:
                    row = json.loads(line)
                except ValueError:
                    continue          # 잘린 줄은 버린다
                if row.get("type") != "system":
                    continue          # 대화에 섞여 들어온 남의 기록
                m = RENAME.search(str(row.get("content", "")))
                if m:
                    name = m.group(1).strip()
    except OSError:
        pass
    return name


def collect():
    rows = []
    if not os.path.isdir(LOGS):
        return rows
    for fn in os.listdir(LOGS):
        if not fn.endswith(".jsonl"):
            continue
        path = os.path.join(LOGS, fn)
        name = find_name(path)
        if not name:                      # 이름 없는 세션은 싣지 않는다
            continue
        rows.append({
            "id": fn[:-6],
            "name": name,
            "mtime": datetime.fromtimestamp(os.path.getmtime(path)),
            "mb": os.path.getsize(path) / 1024 / 1024,
        })
    rows.sort(key=lambda r: r["mtime"], reverse=True)
    return rows


def write_bat(rows):
    """세션 창을 여는 배치 파일. 목록도 한글도 여기 적지 않는다.

    두 가지를 일부러 뺐다.

    **세션 목록** — 전에는 세션마다 `start` 줄을 박아 넣었는데, 이 스크립트가
    실행 도중 이 파일을 다시 쓰기 때문에 cmd 가 읽던 위치를 잃고 마지막 줄을
    건너뛰었다. 지금은 파이썬을 부르는 한 줄만 두고, 창 여는 일은 파이썬이 맡는다.

    **한글** — `chcp 65001` 로 코드페이지를 바꾸면 cmd 가 배치 파일의 바이트를
    세는 방식이 달라진다. cmd 는 한 줄 실행할 때마다 파일을 다시 열어 바이트
    위치로 되짚으므로, 아래쪽에 한글이 있으면 위치가 어긋나 줄 중간부터
    실행된다. 실제로 startup.bat 에서 `'/*' 은 명령이 아닙니다` 같은 조각이
    쏟아졌다. 한글 메시지는 파이썬이 출력한다.
    """
    lines = [
        "@echo off",
        "chcp 65001 > nul",
        "REM ===================================================================",
        "REM  KJC Studio - reopen every named Claude session",
        "REM",
        "REM  Generated by tools/update-sessions.py. Do not edit by hand.",
        "REM  A session joins this list once it has been given a name",
        "REM  with /rename - nothing here needs changing.",
        "REM",
        "REM  KEEP THIS FILE ASCII-ONLY. After `chcp 65001` cmd miscounts the",
        "REM  bytes of its own batch file, so Korean text below makes it lose",
        "REM  its place mid-line. The Korean output comes from Python.",
        "REM ===================================================================",
        "",
        'cd /d "%~dp0"',
        "",
        "REM Rescan the list, then open each session that is not already up.",
        "python tools\\update-sessions.py --open",
        "",
        "ping -n 3 127.0.0.1 > nul",
    ]
    # .bat 은 CRLF 로 저장한다 (.gitattributes 규칙)
    with io.open(BAT, "w", encoding="utf-8", newline="\r\n") as fp:
        fp.write("\n".join(lines) + "\n")


def write_doc(rows):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    L = []
    A = L.append
    A("# 재부팅 후 다시 띄우기")
    A("")
    A("재부팅하거나 창을 닫아도 서버 설정과 대화는 남는다. 아래 방법으로 이어서 쓴다.")
    A("")
    A("> 이 문서는 `tools/update-sessions.py` 가 만든다. 직접 고치지 말 것.")
    A(f"> 마지막 갱신 {now}")
    A("")
    A("## 재부팅하면 저절로 뜬다")
    A("")
    A("`startup.bat` 이 Windows 시작프로그램에 등록되어 있다. 로그인하면 셋이 순서대로 뜬다.")
    A("")
    A("| 순서 | 무엇 | 비고 |")
    A("|---|---|---|")
    A("| 1 | 로컬 서버 `8765`(holdings 미리보기) | 이미 떠 있으면 건너뛴다 |")
    A("| 2 | 브라우저 | `http://localhost:8765/` |")
    A("| 3 | 이름이 붙은 세션 창 전부 | 아래 목록 |")
    A("")
    A("직접 실행해도 된다. 여러 번 실행해도 서버가 겹치지 않는다.")
    A("")
    A("### 서버는 `kis_proxy.py` 다 — `holdings-preview.bat` 이 아니다")
    A("")
    A("`holdings-preview.bat` 은 `http.server` 만 띄운다. 화면은 나오지만")
    A("`/api/kis/*` · `/api/dart/*` 가 전부 `404`(그런 주소 없음) 가 되어 시세도 공시도 안 나온다.")
    A("API 는 `holdings/server/kis_proxy.py` 만 갖고 있다. `startup.bat` 은 이쪽을 띄운다.")
    A("")
    A("확인하려면:")
    A("")
    A("```")
    A("curl http://localhost:8765/api/kis/health     200(정상) 이어야 한다")
    A("```")
    A("")
    A("## 세션만 다시 열기")
    A("")
    A("`resume-sessions.bat` 을 더블클릭하면 아래 세션이 각각 새 창으로 열린다.")
    A("실행할 때 목록을 다시 훑으므로, 세션이 늘어도 그대로 두면 된다.")
    A("")
    A("## 지금 있는 세션")
    A("")
    if not rows:
        A("이름이 붙은 세션이 없다. 각 창에서 `/rename 이름` 을 먼저 쓴다.")
    else:
        A("| 이름 | 세션 ID | 마지막 대화 | 크기 |")
        A("|---|---|---|---|")
        for r in rows:
            A(f"| **{r['name']}** | `{r['id']}` | {r['mtime']:%m-%d %H:%M} | {r['mb']:.0f}MB |")
    A("")
    A("## 하나만 열기")
    A("")
    A("```")
    A("claude --resume <세션 ID>")
    A("```")
    A("")
    A("예를 들어 이렇게 친다.")
    A("")
    A("```")
    if rows:
        A(f"claude --resume {rows[0]['id']}    REM {rows[0]['name']}")
    else:
        A("claude --resume 04fa6a4d-eada-4ddc-9cb9-18ae177540e4")
    A("```")
    A("")
    A("ID 를 모르면 아래처럼 쳐서 목록에서 고른다.")
    A("")
    A("```")
    A("claude --resume")
    A("```")
    A("")
    A("가장 최근 대화 하나만 이어갈 때는 이것으로 충분하다.")
    A("")
    A("```")
    A("claude --continue")
    A("```")
    A("")
    A("## 알아둘 것")
    A("")
    A("- **이미 열려 있는 세션은 건너뛴다.** 같은 세션을 두 창에서 열면 한쪽 기록이 꼬인다.")
    A("  실행할 때마다 `--resume` 으로 떠 있는 창을 확인하므로, 재부팅 뒤가 아니어도 돌려도 된다")
    A("- **창 여는 일은 파이썬이 한다.** 배치 파일에 `start` 줄을 박아 두었더니,")
    A("  이 스크립트가 실행 도중 그 배치 파일을 다시 쓰면서 `cmd` 가 읽던 위치를 잃고")
    A("  마지막 줄을 건너뛰었다. 지금은 `--open` 으로 파이썬이 연다")
    A("- **`.bat` 안에는 한글을 쓰지 않는다.** `chcp 65001` 로 코드페이지를 바꾸면")
    A("  `cmd` 가 배치 파일의 바이트를 세는 방식이 달라진다. `cmd` 는 한 줄 실행할 때마다")
    A("  파일을 다시 열어 바이트 위치로 되짚으므로, 아래쪽에 한글이 있으면 위치가 어긋나")
    A("  **줄 중간부터 실행된다.** 2026-09-16 에 `startup.bat` 에서 이 일이 났다 —")
    A("  `'/*' 은(는) 명령이 아닙니다` 같은 조각이 쏟아지고 세션 창은 열리지 않았다.")
    A("  한글 메시지는 `tools/update-sessions.py` 가 출력한다")
    A("- **`timeout` 대신 `ping -n` 으로 기다린다.** `timeout` 은 입력이 리다이렉트된 채")
    A("  실행되면 `Input redirection is not supported` 로 즉시 죽는다")
    A("- **작업 폴더를 맞춰서 연다.** 네 세션 모두 `C:\\work\\KJCStudio` 에서 돈다.")
    A("  다른 곳에서 열면 상대 경로가 어긋난다. `resume-sessions.bat` 은 알아서 맞춘다")
    A("- **이름이 없는 세션은 목록에 싣지 않는다.** `/rename` 을 쓴 적이 있어야 잡힌다")
    A("- 그냥 `claude` 만 치면 **새 세션**이 생긴다. 기존 대화와 별개다")
    A("- 세션 기록은 `%USERPROFILE%\\.claude\\projects\\C--work-KJCStudio\\` 에 쌓인다")
    A("- 네 세션은 같은 작업 트리를 공유한다. 레인은 `CLAUDE.md` 「세션 역할 분담」 표를 따른다")
    A("")
    A("## 목록이 안 맞을 때")
    A("")
    A("세션을 새로 만들고 이름을 붙였는데 목록에 없으면 아래를 실행한다.")
    A("")
    A("```")
    A("python tools\\update-sessions.py")
    A("```")
    A("")
    with io.open(DOC, "w", encoding="utf-8", newline="\n") as fp:
        fp.write("\n".join(L))


def running_ids():
    """`--resume` 으로 이미 열려 있는 세션 id 를 모은다.

    같은 세션을 두 창에서 열면 한쪽 기록이 꼬인다. 실행할 때마다 확인해서
    떠 있는 것은 건너뛴다. 덕분에 재부팅 뒤가 아니어도 안심하고 돌릴 수 있다.

    `--resume` 없이 연 창(`claude --continue` 등)은 여기 안 잡힌다.
    이 스크립트가 여는 것은 전부 `--resume` 이므로 중복을 막기에는 충분하다.
    """
    import subprocess
    try:
        out = subprocess.run(
            ["powershell", "-NoProfile", "-Command",
             "Get-CimInstance Win32_Process | "
             "Where-Object { $_.CommandLine -match 'resume' } | "
             "ForEach-Object { $_.CommandLine }"],
            capture_output=True, text=True, timeout=25,
        ).stdout or ""
    except Exception:
        return set()
    return set(re.findall(r"resume\s+([0-9a-f-]{36})", out))


def open_windows(rows):
    """세션마다 새 콘솔 창을 띄운다. 이미 열려 있는 것은 건너뛴다.

    배치 파일이 `start` 로 직접 열지 않고 여기서 여는 이유가 있다.
    resume-sessions.bat 은 실행 도중 이 스크립트를 불러 **자기 자신을 다시 쓴다**.
    cmd 는 배치 파일을 한 줄씩 읽어가며 실행하므로, 읽는 중에 파일이 바뀌면
    읽던 위치가 어긋나 남은 줄을 건너뛴다. 창을 여는 일을 파이썬으로 옮겨
    그 구조 자체를 없앴다.
    """
    import subprocess
    live = running_ids()
    opened = skipped = 0
    for r in rows:
        if r["id"] in live:
            print(f"  건너뜀 {r['name']} — 이미 열려 있음")
            skipped += 1
            continue
        # `start` 를 쓰지 않는다. 창 제목을 첫 인자로 넘겼는데, `start` 는
        # **따옴표가 붙어 있을 때만** 그것을 제목으로 본다. 세션 이름에는
        # 공백이 없어서 subprocess 가 따옴표를 안 붙였고, 그래서 `start` 가
        # 이름을 실행 대상으로 읽었다 (2026-09-16).
        #
        #     열기   홈페이지_정리
        #     파일 홈페이지_정리을(를) 찾을 수 없습니다.
        #
        # 창은 뜨지 않았는데 「열었습니다」 로 셌다. 전에는 네 세션이 전부
        # 이미 떠 있어 이 줄을 지나갈 일이 없었던 터라 드러나지 않았다.
        # `startup.bat` 이 부르는 자리이므로 재부팅 때마다 지나간다.
        #
        # CREATE_NEW_CONSOLE 이면 `start` 없이 바로 새 콘솔이 열린다.
        # 제목은 cmd 의 `title` 로 단다.
        subprocess.Popen(
            ["cmd", "/k", f'title {r["name"]} && cd /d "{REPO}" && claude --resume {r["id"]}'],
            creationflags=subprocess.CREATE_NEW_CONSOLE,
        )
        print(f"  열기   {r['name']}")
        opened += 1
    print(f"\n  {opened}개 열었습니다" + (f" · {skipped}개는 이미 떠 있어 건너뛰었습니다" if skipped else ""))


def main():
    quiet = "--quiet" in sys.argv
    rows = collect()
    write_bat(rows)
    write_doc(rows)

    if "--open" in sys.argv:
        if not rows:
            print("이름이 붙은 세션이 없습니다. 각 창에서 /rename 을 먼저 쓰세요.")
            return
        print(f"세션 {len(rows)}개를 엽니다.")
        open_windows(rows)
        return

    if not quiet:
        print(f"세션 {len(rows)}개를 찾았습니다.")
        for r in rows:
            print(f"  {r['name']:<16} {r['id']}  ({r['mtime']:%m-%d %H:%M})")
        print()
        print(f"  {BAT}")
        print(f"  {DOC}")


if __name__ == "__main__":
    main()
